#!/usr/bin/env python3
"""Flat text prompt for starship.

    <path> / <venv> / <branch><dirty> >

No fills, caps or powerline wedges -- colour and the two segment glyphs do
the separating. Everything is a foreground, so the prompt sits directly on
wezterm's graphite background.

Colours are stock Rosé Pine foregrounds. Only the *background* ramp is
desaturated to graphite in this repo (see wezterm/colors.lua), and this
prompt no longer paints a background, so nothing here needs the graphite
substitution.

The git segment is a custom module, not git_branch + git_status:
starship's status markers concatenate per category, so modified +
untracked renders "**", and there is no built-in "is dirty" variable to
collapse them. One command yields "main" or "main*" exactly.

Glyphs are emitted by codepoint, all verified present in CaskaydiaCove.
"""
import os
import sys

# Writes through the symlink into the repo, so the generated file stays tracked.
OUT = os.path.expanduser("~/.config/starship.toml")

# ---------------------------------------------------------------- palette
DIR_FG   = "#e0def4"   # text
GIT_FG   = "#9ccfd8"   # foam
VENV_FG  = "#f6c177"   # gold
SEP_FG   = "#6e6a86"   # muted
DIRTY_FG = "#ebbcba"   # rose -- kept off love so love only ever means "failed"
OK_FG    = "#9ccfd8"   # foam
ERR_FG   = "#eb6f92"   # love

# ---------------------------------------------------------------- glyphs
BRANCH = chr(0xE0A0)
PYTHON = chr(0xE606)

SEP = f"[ / ](fg:{SEP_FG})"


def q(s):
    return '"' + s.replace("\\", "\\\\").replace('"', '\\"') + '"'


# Detached HEAD falls back to a tag, then to a short SHA.
GIT_CMD = (
    'git symbolic-ref --short -q HEAD 2>/dev/null '
    '|| git describe --tags --exact-match 2>/dev/null '
    '|| git rev-parse --short HEAD 2>/dev/null'
)

# The dirty "*" is its own module purely so it can carry its own colour:
# starship substitutes $output as literal text and does not parse style
# markup inside it, so one module cannot emit two colours. This does not
# double the cost -- the branch lookup and the status scan are separate
# commands either way, and only this module runs the expensive one.
# Trailing `exit 0` keeps the module rendering an empty string on a clean
# tree rather than erroring.
DIRTY_CMD = (
    '[ -n "$(git status --porcelain 2>/dev/null | head -n1)" ] && printf "*"; '
    'exit 0'
)

# conda sets CONDA_DEFAULT_ENV to a plain name already; venv/virtualenv
# only sets VIRTUAL_ENV, a full path, so basename it.
VENV_WHEN = 'test -n "$VIRTUAL_ENV$CONDA_DEFAULT_ENV"'
VENV_CMD  = 'basename "${VIRTUAL_ENV:-$CONDA_DEFAULT_ENV}"'

cfg = f'''"$schema" = 'https://starship.rs/config-schema.json'

# Flat text prompt.
#
#   ~/path / {PYTHON} venv / {BRANCH} branch* {chr(0x276F)}
#
# Generated by gen_starship.py -- regenerating overwrites this file.

format = "$directory${{custom.venv}}${{custom.git}}${{custom.git_dirty}}$character"

add_newline = false
command_timeout = 1000

[directory]
format = {q(f"[$path](fg:{DIR_FG})")}
truncation_length = 3
truncation_symbol = "…/"
truncate_to_repo = true

# Active virtualenv/conda env, basename only -- shows nothing outside one.
[custom.venv]
description = "active python virtualenv name"
when = {q(VENV_WHEN)}
command = {q(VENV_CMD)}
format = {q(SEP + f"[{PYTHON} $output](fg:{VENV_FG})")}

# Replaces git_branch + git_status; see the note at the top of the
# generator. Renders nothing outside a repo.
[custom.git]
description = "current branch, tag or short SHA"
when = "git rev-parse --is-inside-work-tree >/dev/null 2>&1"
command = {q(GIT_CMD)}
format = {q(SEP + f"[{BRANCH} $output](fg:{GIT_FG})")}

# Separate module only so the marker can carry its own colour; see the
# generator. Renders nothing on a clean tree.
[custom.git_dirty]
description = "* when the working tree is dirty"
when = "git rev-parse --is-inside-work-tree >/dev/null 2>&1"
command = {q(DIRTY_CMD)}
format = {q(f"[$output](fg:{DIRTY_FG})")}

[character]
format = " $symbol "
success_symbol = "[❯](bold {OK_FG})"
error_symbol = "[❯](bold {ERR_FG})"
'''

with open(OUT, "w", encoding="utf-8") as fh:
    fh.write(cfg)

print(f"wrote {OUT}")
