#!/usr/bin/env python3
"""Waybar-style bar prompt for starship.

One continuous bar rather than separate pills:

    <cap><icon cell><path><chevron><branch><cap> >

Both text segments share LABEL_BG, so the closing cap is the same colour
whether or not the git segment is present. A chevron-chained powerline
version would need each separator's foreground to match the previous
segment's background, so any missing segment orphans a wedge.

The closing cap lives on the character module, the only one guaranteed
to render on every prompt.

The git segment is a custom module, not git_branch + git_status:
starship's status markers concatenate per category, so modified +
untracked renders "**", and there is no built-in "is dirty" variable to
collapse them. One command yields "main" or "main*" exactly.

Glyphs are emitted by codepoint, all verified present in CaskaydiaCove.
"""
import os
import sys

# Writes through the symlink into the repo, so the generated file stays tracked.
OUT = os.path.expanduser("~/.config/starship.toml")

# ---------------------------------------------------------------- palette
# Rosé Pine "graphite" -- stock main foregrounds over a fully desaturated
# background ramp, so nothing behind the bar carries the usual purple tint.
ICON_FG  = "#1e1e1e"   # graphite base -- near-black, sits on the saturated icon cell
LABEL_BG = "#2f2f2f"   # graphite overlay -- the one tone behind the whole bar
DIR_BG   = "#9ccfd8"   # foam, icon cell only

DIR_FG   = "#e0def4"   # text
GIT_FG   = "#9ccfd8"   # same foam as the icon cell
VENV_FG  = "#f6c177"   # gold, python's usual color
CHEV_FG  = "#6e6a86"   # muted
ERR_FG   = "#eb6f92"   # love

# ---------------------------------------------------------------- glyphs
CAP_L  = chr(0xE0B6)   # rounded left cap
CAP_R  = chr(0xE0B4)   # rounded right cap
CHEV   = chr(0xE0B1)   # thin powerline chevron
FOLDER = chr(0xF024B)
BRANCH = chr(0xE0A0)
PYTHON = chr(0xE606)

# ---------------------------------------------------------------- pieces
def label(text, fg):
    return f"[ {text} ](bg:{LABEL_BG} fg:{fg})"

CAP_OPEN  = f"[{CAP_L}](fg:{DIR_BG})"
ICON_CELL = f"[ {FOLDER} ](bg:{DIR_BG} fg:{ICON_FG})"
DIVIDER   = f"[{CHEV}](bg:{LABEL_BG} fg:{CHEV_FG})"
CAP_CLOSE = f"[{CAP_R}](fg:{LABEL_BG})"

def q(s):
    return '"' + s.replace("\\", "\\\\").replace('"', '\\"') + '"'

# Branch name plus a single "*" if anything is dirty -- modified, staged,
# deleted, renamed or untracked. Detached HEAD falls back to a tag, then
# to a short SHA.
GIT_CMD = (
    'b=$(git symbolic-ref --short -q HEAD 2>/dev/null '
    '|| git describe --tags --exact-match 2>/dev/null '
    '|| git rev-parse --short HEAD 2>/dev/null); '
    '[ -n "$b" ] || exit 0; '
    '[ -n "$(git status --porcelain 2>/dev/null | head -n1)" ] && b="$b*"; '
    'printf %s "$b"'
)

# conda sets CONDA_DEFAULT_ENV to a plain name already; venv/virtualenv
# only sets VIRTUAL_ENV, a full path, so basename it.
VENV_WHEN = 'test -n "$VIRTUAL_ENV$CONDA_DEFAULT_ENV"'
VENV_CMD  = 'basename "${VIRTUAL_ENV:-$CONDA_DEFAULT_ENV}"'

cfg = f'''"$schema" = 'https://starship.rs/config-schema.json'

# Waybar-style bar prompt.
#
#   {CAP_L} icon  path {CHEV} venv {CHEV} branch {CAP_R}
#
# The closing cap is carried by [character] -- the only module that
# renders on every single prompt.
#
# Generated by gen_starship.py -- regenerating overwrites this file.

format = "$directory${{custom.venv}}${{custom.git}}$character"

add_newline = false
command_timeout = 1000

[directory]
format = {q(CAP_OPEN + ICON_CELL + label("$path", DIR_FG))}
truncation_length = 3
truncation_symbol = "…/"
truncate_to_repo = true

# Active virtualenv/conda env, basename only -- shows nothing outside one.
[custom.venv]
description = "active python virtualenv name"
when = {q(VENV_WHEN)}
command = {q(VENV_CMD)}
format = {q(DIVIDER + label(f"{PYTHON} $output", VENV_FG))}

# Replaces git_branch + git_status; see the note at the top of the
# generator. Renders nothing outside a repo.
[custom.git]
description = "branch name, with * if the tree is dirty"
when = "git rev-parse --is-inside-work-tree >/dev/null 2>&1"
command = {q(GIT_CMD)}
format = {q(DIVIDER + label(f"{BRANCH} $output", GIT_FG))}

[character]
format = {q(CAP_CLOSE + " $symbol ")}
success_symbol = "[❯](bold {DIR_BG})"
error_symbol = "[❯](bold {ERR_FG})"
'''

with open(OUT, "w", encoding="utf-8") as fh:
    fh.write(cfg)

print(f"wrote {OUT}")
