#!/usr/bin/env python3
"""Generates ~/.config/starship.toml.

The git segment is a custom module rather than git_branch + git_status:
starship's status markers concatenate per category, so modified + untracked
renders "**", and there is no built-in "is dirty" variable to collapse them.

Glyphs are emitted by codepoint, all verified present in CaskaydiaCove.
"""
import os
import sys

# Writes through the symlink into the repo, so the generated file stays tracked.
OUT = os.path.expanduser("~/.config/starship.toml")

# ---------------------------------------------------------------- palette
DIR_FG   = "#e0def4"   # text
GIT_FG   = "#9ccfd8"   # foam
VENV_FG  = "#f6c177"   # gold
SEP_FG   = "#6e6a86"   # muted
DIRTY_FG = "#ebbcba"   # rose -- kept off love so love only ever means "failed"
OK_FG    = "#9ccfd8"   # foam
ERR_FG   = "#eb6f92"   # love

# ---------------------------------------------------------------- glyphs
BRANCH = chr(0xE0A0)
PYTHON = chr(0xE606)

SEP = f"[ / ](fg:{SEP_FG})"


def q(s):
    return '"' + s.replace("\\", "\\\\").replace('"', '\\"') + '"'


# Detached HEAD falls back to a tag, then to a short SHA.
GIT_CMD = (
    'git symbolic-ref --short -q HEAD 2>/dev/null '
    '|| git describe --tags --exact-match 2>/dev/null '
    '|| git rev-parse --short HEAD 2>/dev/null'
)

# Its own module so it can carry its own colour: starship substitutes $output
# as literal text without parsing style markup, so one module cannot emit two.
# `exit 0` renders an empty string on a clean tree instead of erroring.
DIRTY_CMD = (
    '[ -n "$(git status --porcelain 2>/dev/null | head -n1)" ] && printf "*"; '
    'exit 0'
)

# conda gives a plain name; venv only sets VIRTUAL_ENV, a path, so basename it.
VENV_WHEN = 'test -n "$VIRTUAL_ENV$CONDA_DEFAULT_ENV"'
VENV_CMD  = 'basename "${VIRTUAL_ENV:-$CONDA_DEFAULT_ENV}"'

cfg = f'''"$schema" = 'https://starship.rs/config-schema.json'

# Generated by gen_starship.py -- regenerating overwrites this file.

format = "$directory${{custom.venv}}${{custom.git}}${{custom.git_dirty}}$character"

add_newline = false
command_timeout = 1000

[directory]
format = {q(f"[$path](fg:{DIR_FG})")}
truncation_length = 3
truncation_symbol = "…/"
truncate_to_repo = true

[custom.venv]
description = "active python virtualenv name"
when = {q(VENV_WHEN)}
command = {q(VENV_CMD)}
format = {q(SEP + f"[{PYTHON} $output](fg:{VENV_FG})")}

# Replaces git_branch + git_status; see the generator.
[custom.git]
description = "current branch, tag or short SHA"
when = "git rev-parse --is-inside-work-tree >/dev/null 2>&1"
command = {q(GIT_CMD)}
format = {q(SEP + f"[{BRANCH} $output](fg:{GIT_FG})")}

# Separate module so the marker can carry its own colour; see the generator.
[custom.git_dirty]
description = "* when the working tree is dirty"
when = "git rev-parse --is-inside-work-tree >/dev/null 2>&1"
command = {q(DIRTY_CMD)}
format = {q(f"[$output](fg:{DIRTY_FG})")}

[character]
format = " $symbol "
success_symbol = "[❯](bold {OK_FG})"
error_symbol = "[❯](bold {ERR_FG})"
'''

with open(OUT, "w", encoding="utf-8") as fh:
    fh.write(cfg)

print(f"wrote {OUT}")
